blueprint:
  name: Auto light adjustment
  description: >
    Sets a light's brightness and color temperature when it turns on,
    based on the sun elevation (no light sensor required).
  domain: automation
  input:
    trigger_entity:
      name: Trigger entity
      description: The entity that triggers this automation when it turns on.
      selector:
        entity:
          domain: light

    light_entity:
      name: Light entity
      description: The light to control.
      selector:
        entity:
          domain: light

    min_brightness:
      name: Minimum brightness (night)
      description: Brightness when it's darkest outside.
      default: 10
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    max_brightness:
      name: Maximum brightness (midday)
      description: Brightness when the sun is highest.
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
          mode: slider

    warmest_color_temp_kelvin:
      name: Warmest color temp (night)
      description: Warmest Kelvin value used at night.
      default: 2700
      selector:
        number:
          min: 1500
          max: 7000
          unit_of_measurement: "K"

    coolest_color_temp_kelvin:
      name: Coolest color temp (midday)
      description: Coolest Kelvin value used at midday.
      default: 6500
      selector:
        number:
          min: 1500
          max: 7000
          unit_of_measurement: "K"

mode: restart

variables:
  light_entity: !input light_entity
  min_brightness: !input min_brightness
  max_brightness: !input max_brightness
  warmest_color_temp_kelvin: !input warmest_color_temp_kelvin
  coolest_color_temp_kelvin: !input coolest_color_temp_kelvin

  elevation_ratio: >-
    {% set elevation = state_attr('sun.sun', 'elevation') | float(0) %}
    {% set min_elev = -6 %}
    {% set max_elev = 60 %}
    {% set e = elevation %}
    {% if e < min_elev %}
      {% set e = min_elev %}
    {% elif e > max_elev %}
      {% set e = max_elev %}
    {% endif %}
    {% set ratio = (e - min_elev) / (max_elev - min_elev) %}
    {{ ratio }}

  brightness_pct: >-
    {% set ratio = elevation_ratio | float(0) %}
    {% set value = min_brightness + (max_brightness - min_brightness) * ratio %}
    {{ value | round(0) | int }}

  color_temp_kelvin: >-
    {% set ratio = elevation_ratio | float(0) %}
    {% set value = warmest_color_temp_kelvin + (coolest_color_temp_kelvin - warmest_color_temp_kelvin) * ratio %}
    {{ value | round(0) | int }}

trigger:
  - platform: state
    entity_id: !input trigger_entity
    to: "on"

condition: []

action:
  - service: light.turn_on
    target:
      entity_id: "{{ light_entity }}"
    data:
      brightness_pct: "{{ brightness_pct }}"
      kelvin: "{{ color_temp_kelvin }}"
